name: "Engine API schemas sync"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  engine-api-schemas-sync:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: "write"
      contents: "write"
      id-token: "write"
      actions: "read"
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Setup Google Auth ðŸ”§
        # yamllint disable-line rule:line-length
        # nosemgrep: yaml.github-actions.security.third-party-action-not-pinned-to-commit-sha.third-party-action-not-pinned-to-commit-sha
        uses: "google-github-actions/auth@v2"
        with:
          # yamllint disable-line rule:line-length
          workload_identity_provider: "projects/370784745717/locations/global/workloadIdentityPools/github/providers/github"
          service_account: "github-actions@github-400420.iam.gserviceaccount.com"

      - name: 'Set up Cloud SDK'
        # yamllint disable-line rule:line-length
        # nosemgrep: yaml.github-actions.security.third-party-action-not-pinned-to-commit-sha.third-party-action-not-pinned-to-commit-sha
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Generate new types from engine internal openapi
        run: |
          gsutil cp gs://mergify-api-schemas/public.json src/pages/api-schemas.json
          rm -f gha-creds-*.json

      - name: Create the Pull Request
        id: cpr
        # yamllint disable-line rule:line-length
        # nosemgrep: yaml.github-actions.security.third-party-action-not-pinned-to-commit-sha.third-party-action-not-pinned-to-commit-sha
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.MERGIFY_CI_BOT_PAT }}
          author: mergify-ci-bot <mergify-ci-bot@users.noreply.github.com>
          title: "chore: sync Mergify public API schema file"
          body: "Online API docs update is automatically fetched from engine via GCS"
          commit-message: "chore: sync Mergify public API schema file"
          branch: openapi-spec-sync
          base: main

      - name: Report Status
        if: failure()
        # yamllint disable-line rule:line-length
        # nosemgrep: yaml.github-actions.security.third-party-action-not-pinned-to-commit-sha.third-party-action-not-pinned-to-commit-sha
        uses: Mergifyio/gha-slack-notification@main
        with:
          message: "Engine API schemas types sync"
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WORKFLOWS_WEBHOOK_URL }}
